summary: A command-line tool to help you insert the correct compiler options when compiling objects and/or linking libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2 
bin-url: https://github.com/leleliu008/uppm-package-repository-netbsd-10.1-amd64/releases/download/2025.07.23/pkg-config-0.29.2-netbsd-10.1-amd64.release.tar.xz 
bin-sha: 4518769c9edf8e911f730d20ee09ca6a45f0180601c0c6749d2d8138a32ef6c1
